[project]
name = "AIWPapers"
version = "0.0.1"
description = "Artificial Intelligence Weekly Papers"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
authors = [
    {name = "NextAI", email = "nextartifintell@gmail.com"}
]
maintainers = [
    {name = "NextAI", email = "nextartifintell@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"

[project.urls]
Homepage = "https://github.com/Easy-PhD/AIWPapers"
Repository = "https://github.com/Easy-PhD/AIWPapers"
Documentation = "https://Easy-PhD.github.io/AIWPapers"
Source = "https://github.com/Easy-PhD/AIWPapers"
Issues = "https://github.com/Easy-PhD/AIWPapers/issues"
Changelog = "https://github.com/Easy-PhD/AIWPapers/releases"
